/* CREATE TABLE FOR THE AVAILABLE TRANSLATIONS */
CREATE TABLE OD_TRN_TRANSLATIONS
(
  SRC_LANG VARCHAR2(20) NOT NULL
, TRG_LANG VARCHAR2(20) NOT NULL
);

/* INSERTS FOR THE AVAILABLE LANGUAGES */
INSERT INTO OD_TRN_TRANSLATIONS (SRC_LANG, TRG_LANG) VALUES ('es','en');
INSERT INTO OD_TRN_TRANSLATIONS (SRC_LANG, TRG_LANG) VALUES ('es','ca');
INSERT INTO OD_TRN_TRANSLATIONS (SRC_LANG, TRG_LANG) VALUES ('es','fr');
INSERT INTO OD_TRN_TRANSLATIONS (SRC_LANG, TRG_LANG) VALUES ('es','de');
INSERT INTO OD_TRN_TRANSLATIONS (SRC_LANG, TRG_LANG) VALUES ('es','ru');

/* CREATE TABLE FOR THE AVAILABLE TRANSLATIONS */
CREATE TABLE OD_TRN_VALS_TO_TRANS
(
  DATASET_NAME VARCHAR2(50) NOT NULL
, CSV_COLS VARCHAR2(4000)
, XML_JSON_KEYS VARCHAR2(4000)
);

/* CREATE TABLE FOR THE VALUES OF THE JSON FILES */
CREATE TABLE OD_TRN_JSON_TRANS
(
  JSON_KEY VARCHAR2(500) NOT NULL
, ORIGINAL_VAL VARCHAR2(4000) NOT NULL
, TRANSLATED_VAL VARCHAR2(4000) NOT NULL
);

/* CREATE TABLE FOR THE LANGUAGES OF THE CKAN PORTAL */
/* SRC_LANG HAS TO BE en */
CREATE TABLE OD_TRN_CKAN_PORTAL_LANGS
(
  SRC_LANG VARCHAR2(10) NOT NULL
, TRG_LANG VARCHAR2(10) NOT NULL
);

/* CREATE TABLES FOR THE TRANSLATIONS OF THE CKAN PORTAL */
/* OD_TRN_CKAN_PORTAL_ORIGINAL: ORIGINAL VALUES FROM POs */
/* OD_TRN_CKAN_PORTAL_TRANS: FILTERED AND TRANSLATED VALS */
/* OD_TRN_CKAN_PORTAL_NO_FILTER: ROWS THAT ARE NOT TRANSLATED */
CREATE TABLE OD_TRN_CKAN_PORTAL_ORIGINAL
(
  NUM_LINE VARCHAR2(4000) NOT NULL
, ORIGINAL VARCHAR2(4000)
, PO_ROW VARCHAR2(4000)
);
CREATE TABLE OD_TRN_CKAN_PORTAL_TRANS
(
  NUM_LINE VARCHAR2(4000) NOT NULL
, FILTERED VARCHAR2(4000)
, TRANSLATED VARCHAR2(4000)
);
CREATE TABLE OD_TRN_CKAN_PORTAL_NO_FILTER
(
  NUM_LINE VARCHAR2(4000) NOT NULL
, ROW_VALUE VARCHAR2(4000)
);
